name: Flutter CI

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch


jobs:
  # Build for Windows
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.29.0

    - name: Install dependencie
      run: flutter pub get

    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: bash scripts/prepare.sh windows
      run: bash scripts/prepare.sh windows

    - name: Build Windows
      run: flutter build windows

    - run: ls -R

    - name: Compile .ISS to .EXE Installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: scripts/windows/setup.iss

    - run: ls -R
    
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: anyportal-windows
        path: build/windows/x64/runner/Release

    - name: Upload Windows setup artifacts
      uses: actions/upload-artifact@v4
      with:
        name: anyportal-windows-setup
        path: scripts/windows/Output/mysetup.exe
